// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CPDevice struct {
	ID        string `json:"id"`
	GatewayID string `json:"gateway_id"`
	Auth      string `json:"auth"`
	DeviceID  string `json:"device_id"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
