name: Run Go Test

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - name: Setup Profile
        shell: bash
        run: |
          echo 'export GOPATH="$HOME/go"' >>~/.bash_profile
          echo 'PATH="$GOPATH/bin:$PATH"' >>~/.bash_profile
      - name: Run Test
        shell: bash
        run: go test ./...